# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4abd7c61140645f465cc4b2933f280a654138adb6a54ab31fe4c57180d329f6c1e65b21024cc97c003b253782c233f52307f656815d67521afeb687aed2c09a0

test:
  secret_key_base: a84f82caf41bab6c7d58bb8bf0848f5f20fbb19ce6a3e785229492b4f6fa3e4798a9d2f663b26c1d81a44ddcafc87237cc00457a0672effcbe0b59c590e913d4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
